### ISSUE TITLE
Update deps and resolve security advisories

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/pages-mailer#13]
## Story
In order to maintain a secure system, Pages Operators want to resolve outstanding security advisories.

## Acceptance Criteria
* [ ] No security advisories are present

--- 

## Security considerations
Resolves security advisories.

## Implementation sketch
* [ ] Upgrade `tap` to latest 16.x version
* [ ] Upgrade `dotenv` to latest 16.x version

**Comment by apburnes** [comment]
N/A
