### ISSUE TITLE
Update mailer app to cflinuxfs4 and node 18

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-mailer#27]
Update the mailer CF app stack to cflinuxfs4 and upgrade Nodejs to v18.

## Acceptance Criteria

- [x] Deploys app to cflinuxfs4
- [x] Updates to Nodejs v18
- [x] Updates CI tests to use Nodejs v18

**Comment by Ephraim-G** [comment]
successfully updated to cflinuxfs4 and deployed.
